In [30]:
import pandas as pd

orders = pd.read_csv('data/raw/olist_orders_dataset.csv')
order_items = pd.read_csv('data/raw/olist_order_items_dataset.csv')
order_reviews = pd.read_csv('data/raw/olist_order_reviews_dataset.csv')
customers = pd.read_csv('data/raw/olist_customers_dataset.csv')
products = pd.read_csv('data/raw/olist_products_dataset.csv')
sellers = pd.read_csv('data/raw/olist_sellers_dataset.csv')
category_translation = pd.read_csv('data/raw/product_category_name_translation.csv')

print("Before merge, order_items shape:", order_items.shape)

Before merge, order_items shape: (112650, 7)

In [31]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [32]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [33]:
# # Step 1: order_items + orders
# df = order_items.merge(orders, on='order_id', how='left')
# print("After merging orders:", df.shape)

# Sanity check on reviews before merging
print("Review rows vs unique order_ids in reviews:", 
      order_reviews.shape[0], order_reviews['order_id'].nunique())
# this means that 99224-98673 = 551 have submiited their revies twice or revised

Review rows vs unique order_ids in reviews: 99224 98673

In [34]:
# Step 1: order_items + orders
df = order_items.merge(orders, on='order_id', how='left')
print("After merging orders:", df.shape)

After merging orders: (112650, 14)

In [35]:
df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18 00:00:00
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01 00:00:00
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22,2017-11-10 00:00:00
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,2017-08-15 00:04:32,2017-08-15 19:02:53,2017-08-16 21:59:40,2017-08-25 00:00:00
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28 00:00:00

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 14 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   shipping_limit_date            112650 non-null  object
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  object
 8   order_status                   112650 non-null  object
 9   order_purchase_timestamp       112650 non-null  object
 10  order_approved_at              112635 non-null  object
 11  order_delivered_carrier_date   111456 non-null  object
 12  order_delivered_customer_date  110196 non-null  object
 13  order_estimated_delivery_date  112650 non-null  object
dtypes: float64(2), int64(1), object(11)
memory usage: 12.0+ MB

In [37]:
order_reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [38]:
print(order_reviews.columns.tolist())

['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

In [39]:
order_reviews[order_reviews.duplicated(subset='order_id', keep=False)].sort_values('order_id')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
25612,89a02c45c340aeeb1354a24e7d4b2c1e,0035246a40f520710769010f752e7507,5,NaN,NaN,2017-08-29 00:00:00,2017-08-30 01:59:12
22423,2a74b0559eb58fc1ff842ecc999594cb,0035246a40f520710769010f752e7507,5,NaN,Estou acostumada a comprar produtos pelo barat...,2017-08-25 00:00:00,2017-08-29 21:45:57
22779,ab30810c29da5da8045216f0f62652a2,013056cfe49763c6f66bda03396c5ee3,5,NaN,NaN,2018-02-22 00:00:00,2018-02-23 12:12:30
68633,73413b847f63e02bc752b364f6d05ee9,013056cfe49763c6f66bda03396c5ee3,4,NaN,NaN,2018-03-04 00:00:00,2018-03-05 17:02:00
854,830636803620cdf8b6ffaf1b2f6e92b2,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:06
...,...,...,...,...,...,...,...
27465,5e78482ee783451be6026e5cf0c72de1,ff763b73e473d03c321bcd5a053316e8,3,NaN,Não sei que haverá acontecido os demais chegaram,2017-11-18 00:00:00,2017-11-18 09:02:48
41355,39de8ad3a1a494fc68cc2d5382f052f4,ff850ba359507b996e8b2fbb26df8d03,5,NaN,Envio rapido... Produto 100%,2017-08-16 00:00:00,2017-08-17 11:56:55
18783,80f25f32c00540d49d57796fb6658535,ff850ba359507b996e8b2fbb26df8d03,5,NaN,"Envio rapido, produto conforme descrito no anu...",2017-08-22 00:00:00,2017-08-25 11:40:22
92230,870d856a4873d3a67252b0c51d79b950,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-20 18:50:16
53962,5476dd0eaee7c4e2725cafb011aa758c,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-21 13:24:55

In [40]:
# we can see that 1st order id have submitted two review, we j=want latest one only

In [41]:
# Convert to datetime so sorting actually works chronologically (not as text)
order_reviews['review_creation_date'] = pd.to_datetime(order_reviews['review_creation_date'])

# Sort by date, then keep only the latest review per order_id
order_reviews_dedup = order_reviews.sort_values('review_creation_date').drop_duplicates(subset='order_id', keep='last')

print("Original review rows:", order_reviews.shape[0])
print("After dedup:", order_reviews_dedup.shape[0])
print("Unique order_ids:", order_reviews['order_id'].nunique())

Original review rows: 99224
After dedup: 98673
Unique order_ids: 98673

In [42]:
# second merge
# Step 2: + reviews (deduplicated)
df = df.merge(order_reviews_dedup[['order_id', 'review_score']], on='order_id', how='left')
print("After merging reviews:", df.shape)

# Step 3: + customers
df = df.merge(customers, on='customer_id', how='left')
print("After merging customers:", df.shape)

# Step 4: + products
df = df.merge(products[['product_id', 'product_category_name']], on='product_id', how='left')
print("After merging products:", df.shape)

# Step 5: + sellers
df = df.merge(sellers, on='seller_id', how='left')
print("After merging sellers:", df.shape)

# Step 6: + category translation
df = df.merge(category_translation, on='product_category_name', how='left')
print("After merging category translation:", df.shape)

print()
print("Final columns:", df.columns.tolist())

After merging reviews: (112650, 15)
After merging customers: (112650, 19)
After merging products: (112650, 20)
After merging sellers: (112650, 23)
After merging category translation: (112650, 24)

Final columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'review_score', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'product_category_name', 'seller_zip_code_prefix', 'seller_city', 'seller_state', 'product_category_name_english']

In [43]:
# Convert date columns to actual datetime objects first (they're currently just text/object dtype)
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])
df['order_estimated_delivery_date'] = pd.to_datetime(df['order_estimated_delivery_date'])

# How many rows have a missing delivered date? (order never delivered, or still in transit)
print("Missing delivered_customer_date:", df['order_delivered_customer_date'].isna().sum())
print("Total rows:", df.shape[0])

Missing delivered_customer_date: 2454
Total rows: 112650

In [44]:
df['order_purchase_timestamp']

0        2017-09-13 08:59:02
1        2017-04-26 10:53:06
2        2018-01-14 14:33:31
3        2018-08-08 10:00:35
4        2017-02-04 13:57:51
                 ...
112645   2018-04-23 13:57:06
112646   2018-07-14 10:26:46
112647   2017-10-23 17:07:56
112648   2017-08-14 23:02:59
112649   2018-06-09 17:00:18
Name: order_purchase_timestamp, Length: 112650, dtype: datetime64[ns]

In [45]:
df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,review_score,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,product_category_name,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,5.0,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ,cool_stuff,27277,volta redonda,SP,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,4.0,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP,pet_shop,3471,sao paulo,SP,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,5.0,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG,moveis_decoracao,37564,borda da mata,MG,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,4.0,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP,perfumaria,14403,franca,SP,perfumery
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,5.0,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP,ferramentas_jardim,87900,loanda,PR,garden_tools
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,...,5.0,0c9aeda10a71f369396d0c04dce13a64,65077,sao luis,MA,utilidades_domesticas,88303,itajai,SC,housewares
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,...,5.0,0da9fe112eae0c74d3ba1fe16de0988b,81690,curitiba,PR,informatica_acessorios,1206,sao paulo,SP,computers_accessories
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,...,5.0,cd79b407828f02fdbba457111c38e4c4,4039,sao paulo,SP,esporte_lazer,80610,curitiba,PR,sports_leisure
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,...,5.0,eb803377c9315b564bdedad672039306,13289,vinhedo,SP,informatica_acessorios,4733,sao paulo,SP,computers_accessories
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,...,5.0,cd76a00d8e3ca5e6ab9ed9ecb6667ac4,18605,botucatu,SP,cama_mesa_banho,14940,ibitinga,SP,bed_bath_table

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   shipping_limit_date            112650 non-null  object
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  object
 8   order_status                   112650 non-null  object
 9   order_purchase_timestamp       112650 non-null  datetime64[ns]
 10  order_approved_at              112635 non-null  object
 11  order_delivered_carrier_date   111456 non-null  object
 12  order_delivered_customer_date  110196 non-null  datetime64[ns]
 13  order_estimated_delivery_date  112650 non-null  datetime64[ns]
 14  review_score                   111708 non-null  float64
 15  customer_unique_id             112650 non-null  object
 16  customer_zip_code_prefix       112650 non-null  int64
 17  customer_city                  112650 non-null  object
 18  customer_state                 112650 non-null  object
 19  product_category_name          111047 non-null  object
 20  seller_zip_code_prefix         112650 non-null  int64
 21  seller_city                    112650 non-null  object
 22  seller_state                   112650 non-null  object
 23  product_category_name_english  111023 non-null  object
dtypes: datetime64[ns](3), float64(3), int64(3), object(15)
memory usage: 20.6+ MB

In [47]:
print(df[df['order_delivered_customer_date'].isna()]['order_status'].value_counts())
#reason that delivery daye column 11 is missing that answer is given in status112650-110196 = 2454

order_status
shipped        1185
canceled        535
invoiced        359
processing      357
delivered         8
unavailable       7
approved          3
Name: count, dtype: int64

In [48]:
print(df[df['order_delivered_customer_date'].isna()]['order_status'].value_counts().sum())

2454

In [49]:
# Recreate delay_flag using pandas' nullable boolean dtype, which properly supports NA
df['delay_flag'] = (df['order_delivered_customer_date'] > df['order_estimated_delivery_date']).astype('boolean')
df.loc[df['order_delivered_customer_date'].isna(), 'delay_flag'] = pd.NA

print(df['delay_flag'].dtype)
print(df['delay_flag'].value_counts(dropna=False))

boolean
delay_flag
False    101481
True       8715
<NA>       2454
Name: count, dtype: Int64

In [50]:
# For each seller, what fraction of their delivered orders were delayed?
# We use dropna() because delay_flag has NaN for undelivered orders — we only want
# to compute delay rate among orders we actually know the outcome for.

seller_delay = (
    df.dropna(subset=['delay_flag'])
      .groupby('seller_id')['delay_flag']
      .mean()
      .rename('seller_delay_rate')
)

print(seller_delay)
print()
print("Number of sellers:", seller_delay.shape[0])

seller_id
0015a82c2db000af6aaaf3ae2ecb0532         0.0
001cca7ae9ae17fb1caed9dfb1094831    0.055556
002100f778ceb8431b7a1020ff7ab48f    0.166667
003554e2dce176b5555353e4f3555ac8         0.0
004c9cd9d87a3c30c522c48c4fc07416    0.077381
                                      ...
ffc470761de7d0232558ba5e786e57b7    0.066667
ffdd9f82b9a447f6f8d4b91554cc7dd3         0.0
ffeee66ac5d5a62fe688b9d26f83f534    0.142857
fffd5413c0700ac820c7069d66d98c89    0.137931
ffff564a4f9085cd26170f4732393726         0.0
Name: seller_delay_rate, Length: 2970, dtype: Float64

Number of sellers: 2970

In [51]:
df = df.merge(seller_delay, on='seller_id', how='left')
print("After merging seller_delay_rate:", df.shape)
print(df[['seller_id', 'seller_delay_rate']].head(10))

After merging seller_delay_rate: (112650, 26)
                          seller_id  seller_delay_rate
0  48436dade18ac8b2bce089ec2a041202           0.068027
1  dd7ddc04e1b6c2c614352b383efe2d36           0.147887
2  5b51032eddd242adc84c38acab88f23d                0.0
3  9d7a1d34a5052409006425275ba1c2b4             0.0625
4  df560393f3a51e74553ab94004ba5c87           0.074074
5  6426d21aca402a131fc0a5d0960a3c90           0.043478
6  7040e82f899a04d1b434b795a43b4617           0.089686
7  5996cddab893a4652a15592fb58ab8db                0.0
8  a416b6a846a11724393025641d4edd5e              0.125
9  ba143b05f0110f0dc71ad71b4466ce92           0.154762

In [52]:
df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,customer_zip_code_prefix,customer_city,customer_state,product_category_name,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english,delay_flag,seller_delay_rate
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,28013,campos dos goytacazes,RJ,cool_stuff,27277,volta redonda,SP,cool_stuff,False,0.068027
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,15775,santa fe do sul,SP,pet_shop,3471,sao paulo,SP,pet_shop,False,0.147887
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,35661,para de minas,MG,moveis_decoracao,37564,borda da mata,MG,furniture_decor,False,0.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,12952,atibaia,SP,perfumaria,14403,franca,SP,perfumery,False,0.0625
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,13226,varzea paulista,SP,ferramentas_jardim,87900,loanda,PR,garden_tools,False,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,...,65077,sao luis,MA,utilidades_domesticas,88303,itajai,SC,housewares,False,0.021277
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,...,81690,curitiba,PR,informatica_acessorios,1206,sao paulo,SP,computers_accessories,False,0.066667
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,...,4039,sao paulo,SP,esporte_lazer,80610,curitiba,PR,sports_leisure,False,0.022801
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,...,13289,vinhedo,SP,informatica_acessorios,4733,sao paulo,SP,computers_accessories,False,0.0
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,...,18605,botucatu,SP,cama_mesa_banho,14940,ibitinga,SP,bed_bath_table,False,0.09589

In [53]:
# category_review_score: average review score per product category
category_review = (
    df.dropna(subset=['review_score'])
      .groupby('product_category_name_english')['review_score']
      .mean()
      .rename('category_review_score')
)

# seller_review_score: average review score per seller
seller_review = (
    df.dropna(subset=['review_score'])
      .groupby('seller_id')['review_score']
      .mean()
      .rename('seller_review_score')
)

# order_volume: how many order-items each seller has handled (a simple count, not a mean)
seller_volume = (
    df.groupby('seller_id')
      .size()
      .rename('order_volume')
)

# Merge all three back onto df
df = df.merge(category_review, on='product_category_name_english', how='left')
df = df.merge(seller_review, on='seller_id', how='left')
df = df.merge(seller_volume, on='seller_id', how='left')

print("Final shape:", df.shape)
print(df[['product_category_name_english', 'category_review_score', 
           'seller_id', 'seller_review_score', 'seller_delay_rate', 'order_volume']].head(10))

Final shape: (112650, 29)
  product_category_name_english  category_review_score  \
0                    cool_stuff               4.147262
1                      pet_shop               4.184306
2               furniture_decor               3.904848
3                     perfumery               4.165932
4                  garden_tools               4.045423
5                    housewares               4.053339
6                     telephony               3.945922
7                  garden_tools               4.045423
8                 health_beauty               4.141635
9               books_technical               4.363636

                          seller_id  seller_review_score  seller_delay_rate  \
0  48436dade18ac8b2bce089ec2a041202             4.046358           0.068027
1  dd7ddc04e1b6c2c614352b383efe2d36             3.760563           0.147887
2  5b51032eddd242adc84c38acab88f23d             3.785714                0.0
3  9d7a1d34a5052409006425275ba1c2b4             3.750000             0.0625
4  df560393f3a51e74553ab94004ba5c87             3.724138           0.074074
5  6426d21aca402a131fc0a5d0960a3c90             4.173913           0.043478
6  7040e82f899a04d1b434b795a43b4617             3.528889           0.089686
7  5996cddab893a4652a15592fb58ab8db             5.000000                0.0
8  a416b6a846a11724393025641d4edd5e             4.160221              0.125
9  ba143b05f0110f0dc71ad71b4466ce92             4.423529           0.154762

   order_volume
0           151
1           143
2            14
3            16
4            29
5            23
6           228
7             1
8           181
9            86

In [54]:
df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,product_category_name,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english,delay_flag,seller_delay_rate,category_review_score,seller_review_score,order_volume
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,cool_stuff,27277,volta redonda,SP,cool_stuff,False,0.068027,4.147262,4.046358,151
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,pet_shop,3471,sao paulo,SP,pet_shop,False,0.147887,4.184306,3.760563,143
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,moveis_decoracao,37564,borda da mata,MG,furniture_decor,False,0.0,3.904848,3.785714,14
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,perfumaria,14403,franca,SP,perfumery,False,0.0625,4.165932,3.750000,16
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,ferramentas_jardim,87900,loanda,PR,garden_tools,False,0.074074,4.045423,3.724138,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,...,utilidades_domesticas,88303,itajai,SC,housewares,False,0.021277,4.053339,4.347826,47
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,...,informatica_acessorios,1206,sao paulo,SP,computers_accessories,False,0.066667,3.932408,4.266667,15
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,...,esporte_lazer,80610,curitiba,PR,sports_leisure,False,0.022801,4.106981,4.447712,307
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,...,informatica_acessorios,4733,sao paulo,SP,computers_accessories,False,0.0,3.932408,4.388889,54
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,...,cama_mesa_banho,14940,ibitinga,SP,bed_bath_table,False,0.09589,3.897469,3.819444,74

In [55]:
os.makedirs('data/processed', exist_ok=True)
print("Now exists?", os.path.exists('data/processed'))

Now exists? True

In [56]:
df.to_csv('data/processed/master_df.csv', index=False)
print("Saved! Shape:", df.shape)

check = pd.read_csv('data/processed/master_df.csv')
print("Re-loaded shape:", check.shape)

Saved! Shape: (112650, 29)
Re-loaded shape: (112650, 29)

In [2]:
os.chdir('..')
print("Now in:", os.getcwd())
print("Does data/processed exist here?", os.path.exists('data/processed'))
if os.path.exists('data/processed'):
    print("Contents:", os.listdir('data/processed'))

Now in: C:\Users\Aanchal Shah\OneDrive\Desktop\InsightAgent
Does data/processed exist here? True
Contents: ['.ipynb_checkpoints', 'master_df.csv']